-
  name: Execute two commands on boston nodes
  hosts: boston_nodes
  tasks:
    -
      name: Execute a date command
      command: date
    -
      name: Execute a command to display hosts file
      command: cat /etc/hosts